### ISSUE TITLE
Tail Message

### ISSUE THREAD

**Issue by KA0KDW** [Mason10198/SkywarnPlus#64]
**Describe the bug**
A clear and concise description of what the bug is.I have changed all items related to the tail message to match the instructions including in the RPT.CONF ajd am not receiving tail messages while the node has acidify dyeing the specified time intervals. Should the tail message be for all alerts or is it only for specifc alerts?  Don’t know that I’d is a “reproducible issue” or if I’m just missing something.

**Comment by Mason10198** [comment]
All alerts are added to the tailmessage by default. If desired, alerts can be blocked using the blocking section of `config.yaml`:
```yaml
Blocking:
  # List of globally blocked events. These alerts are ignored across the entire SkywarnPlus operation.
  # Use a case-sensitive list. Wildcards can be used.
  # Example:
  # GlobalBlockedEvents:
  #   - Flood Watch
  #   - '*Statement'
  #   - '*Advisory'
  GlobalBlockedEvents:

  # List of events blocked from being announced when received. These alerts will still be added to the tail message.
  # Use a case-sensitive list.
  SayAlertBlockedEvents:

  # List of events blocked from being added to the tail message. These alerts will still be announced when received.
  # Use a case-sensitive list.
  TailmessageBlockedEvents:
```

Please check to make sure the file `/tmp/SkywarnPlus/wx-tail.wav` exists.
- If it DOES exist:
  - SkywarnPlus is working correctly and you have something configured wrong with Asterisk. Check Asterisk logs.
  - Provide more information - copy of your `rpt.conf` file for starters
- If it does NOT exist:
  - User configuration error or bug in SkywarnPlus. Please check SWP logs (enable debug mode if necessary)
  - Provide more information - copy of your `config.yaml` file and SWP logs
